### ISSUE TITLE
ERROR in ENOENT ngx-stepper.style.scss

### ISSUE THREAD

**Issue by gise88** [KeitaElric/ngx-stepper#1]
Hi! Thank you for your work! I wanted to notify you about two errors that I get when I install your library from npm.

1) When I simply try to run I get those errors on my chrome console:

![screenshot_20170810_015220](https://user-images.githubusercontent.com/6855163/29148588-b760ad92-7d6e-11e7-9772-ba12fd6f8b62.jpeg)

2) when I compile in aot I receive this error:

```
ERROR in ENOENT: no such file or directory, open '<MY PATH>/frontend/node_modules/ngx-stepper/dist/lib/ngx-stepper.style.scss'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '<MY PATH>/frontend/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```
This one was easily resolved by adding [this scss](https://github.com/KeitaElric/ngx-stepper/blob/master/src/ngx-stepper/ngx-stepper.style.scss) inside the dist folder. 

Probably is because I have choosen tu use scss in my project? I don't know..

**Comment by KeitaElric** [comment]
Oh my bad, it will be fix for 1 hour. Thanks :smile

**Comment by KeitaElric** [comment]
Resolved at v1.1.3

**Comment by KeitaElric** [comment]
Resolved at lastest version.

**Comment by gise88** [comment]
Really, thank you so much! 
While I am here: is there any way to customize colors of the header bar, stepper-number, etc?

**Comment by KeitaElric** [comment]
Just overwrite css class as you want

**Comment by BobbieBarker** [comment]
This issue seems to have resurfaced in the `1.1.5` version. 
![image](https://user-images.githubusercontent.com/4307099/32869130-37eac86e-ca2a-11e7-9c6e-8c15dcf69291.png)
