### ISSUE TITLE
ngFor not working on ngx-step

### ISSUE THREAD

**Issue by bharathmuppa** [KeitaElric/ngx-stepper#3]
I want to loop through the ngx-step using the following code.

`           <ngx-stepper #stepperDemo="stepper" [options]="options">
            <ngx-step [label]="state.Label" *ngFor="let state of statusList" >
             <ngx-step-body>
             sample
              </ngx-step-body>
               <ngx-step-actions>
                 <button md-button class="md-primary md-raised" (click)="nextStep()">Continue</button>
                <button md-button class="md-primary" (click)="stepperDemo.back()">Cancel</button>
               </ngx-step-actions>
               </ngx-step>
            </ngx-stepper>`

error:  Cannot read property 'currentStep' of undefined

I have gone through the googling but didn't find out anything .

**Comment by anvial** [comment]
Any suggestions to use *ngIf and *ngFor on <ngx-step> tag?

**Comment by bharathmuppa** [comment]
Angular material now has stepper component .. cheers

**Comment by GaikwadPratik** [comment]
Any luck fixing issue with ngFor?
