### ISSUE TITLE
Build broken with @angular/material 2.0.0-beta.12

### ISSUE THREAD

**Issue by lihanyu23** [KeitaElric/ngx-stepper#4]
The build is broken with the new beta version 2.0.0-beta.12.

This is due to the renaming of all modules and components from "Md" to "Mat" in the new release of  material 2. Using ngx-stepper with this version will cause "Unexpected value 'undefined' imported by the module 'NgxStepperModule'" at runtime.

**Comment by anvial** [comment]
Is this problem planned to be fixed?

**Comment by lihanyu23** [comment]
#5

**Comment by KeitaElric** [comment]
Thanks for contributed.
