### ISSUE TITLE
404 on ngx-stepper.style.scss

### ISSUE THREAD

**Issue by BobbieBarker** [KeitaElric/ngx-stepper#6]
I'm currently facing this issue:

![image](https://user-images.githubusercontent.com/4307099/32913806-5340aff4-cac8-11e7-8963-087eb97d3256.png)

I am looking into it and will submit a PR if I can fix the issue. Any assistance is welcomed.

**Comment by BobbieBarker** [comment]
This is definitely an issue with your build step not treating your `.scss` properly. I unfortunately cannot pursue this any further, but you might want to consider updating your angular stuff to latest especially the compiler.

**Comment by KeitaElric** [comment]
Please check for version 1.1.6 to see it fixed.
